version: "3.1"
services:
  my_db:
    image: mariadb
    container_name: my_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
      - SQL_CLIENT_PORT=3307
    volumes:
      - ./:/scripts
    ports:
      - 3306
    restart: unless-stopped
  assign5_rollingavg:
    container_name: assign5_rollingavg
    depends_on:
      - my_db
    build:
      context: .
      dockerfile: Dockerfile
    image: assign5_rollingavg
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
    restart: unless-stopped
